image: python:3.6-slim

before_script:
    - python -V # Print out python version for debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    
stages:
    - build
    - test
    - deploy

cache:
  paths:
    - .cache/pip
    - venv/
    - src/yggscr/__build__.py

job_build:
    stage: build
    script:
        - echo "Building the app"
        - python setup.py build
        - python setup.py -q install
    only:
        - branches
        - tags
        - merge_requests

job_test:
    stage: test
    script:
        - echo "Running tests"
        - apt-get update -qq && apt-get install -y nodejs nodejs-legacy
        - pip install -r requirements.txt
        - python -m pytest
    dependencies:
        - job_build
    only:
        - branches
        - merge_requests
    except:
        - master

job_deployment_staging:
    stage: deploy

    script:
        - echo "Deploy MASTER BRANCH of the app into staging"
        - python setup.py build
        - python setup.py -q install

    environment:
        name: staging
    only:
        - master

job_deploy_prod:
    stage: deploy
    script:
        - echo "Deploy MASTER BRANCH into the production server"
        - python setup.py sdist
    environment:
        name: production
#    allow_failure: false
    when: manual
    only:
        - master

