image: python:3.6-slim

before_script:
    - python -V # Print out python version for debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    
stages:
    - build
    - test
    - deploy

cache:
  paths:
    - venv/
    - src/yggscr/__build__.py
    - .cache/pip

# Only build on merge requests
# As push to dev or master is not allowed anyway
job_build:
    stage: build
    only:
        - merge_requests
    
    script:
        - echo "Building the app"
        - python setup.py build
        - python setup.py -q install

# Only test on merge requests
# As push to dev or master is not allowed anyway
# Don't perform tests on master
job_test:
    stage: test
    dependencies:
        - job_build
    only:
        - merge_requests
    except:
        - master
    
    script:
        - echo "Running tests"
        - apt-get update -qq && apt-get install -y nodejs nodejs-legacy
        - pip install -r requirements-dev.txt
        - pytest --fixtures tests/
        - pytest --collect-only tests/
        - pytest -s tests/

# Staging master branch
job_deployment_staging:
    stage: deploy
    environment:
        name: staging
    only:
        - master

    script:
        - echo "Deploy master branch of the app into staging"
        - python setup.py build
        - python setup.py -q install

# Manual job to production
job_deploy_prod:
    stage: deploy
    environment:
        name: production
#    allow_failure: false
    when: manual
    only:
        - master

    script:
        - echo "Deploy master branch into the production server"
        - python setup.py sdist
