language: python

matrix:
  include:
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

#virtualenv:
#  system_site_packages: true

addons:
  apt:
    packages:
      - python3-setuptools
      - nodejs

branches:
  only:
  - dev
  - master

before_install:
  - python --version
  - uname -a
  - lsb_release -a

# command to install dependencies
install:
  - pip install coveralls codecov
  - python3 setup.py -q install

# command to run tests
script:
  - pip install -r requirements-dev.txt
  - pytest --fixtures tests/
  - pytest tests/

notifications:
  email:
    on_success: never
    on_failure: always

after_success:
    - coveralls
    - codecov
