language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
virtualenv:
  system_site_packages: true

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
    - os: linux
      dist: stretch
      sudo: required
    - os: linux
      dist: jessie
      sudo: required

# command to install dependencies
install:
  - python3 setup.py -q install

# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
