language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

virtualenv:
  system_site_packages: true

sudo: required

addons:
  apt:
    packages:
      - python3-setuptools

matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: precise

# command to install dependencies
install:
  - python3 setup.py -q install

# command to run tests
script:
  - nosetests -w tests
