language: python

matrix:
  include:
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

#virtualenv:
#  system_site_packages: true

addons:
  apt:
    packages:
      - python3-setuptools

branches:
  only:
  - dev
  - master

# command to run tests
script:
  - pip install pytest-cov
  - pytest

before_install:
  - python --version
  - uname -a
  - lsb_release -a

# command to install dependencies
install:
  - pip install coveralls
  - python3 setup.py -q install


notifications:
  email:
    on_success: never
    on_failure: always

after_success:
    - coveralls
