language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

#virtualenv:
#  system_site_packages: true

addons:
  apt:
    packages:
      - python3-setuptools

branches:
  only:
  - dev
  - master

matrix:
  include:
    - os: linux
      sudo: false
      dist: xenial
    - os: linux
      sudo: required
      dist: xenial

# command to install dependencies
install:
  - python3 setup.py -q install

# command to run tests
script:
  - nosetests -w tests
