version: "3.7"

services:
    nginx:
        depends_on:
            - stage
        build:
            context: ./nginx
        volumes:
            - type: volume
              source: usocket
              target: /run/ygg/
              volume:
                  nocopy: true
            - type: volume
              source: conf
              target: /opt/yggscr/conf/
              volume:
                  nocopy: true
        ports:
            - "8333:80"

    stage:
        build:
            context: ../
            dockerfile: $PWD/docker/stage/Dockerfile
        volumes:
            - "usocket:/run/ygg/"
            - "conf:/opt/yggscr/conf/"

    yserver:
        build:
            context: ../
            dockerfile: $PWD/docker/yserver/Dockerfile
        ports:
            - "8333:8333"


volumes:
    usocket:
    conf:
